import argparse
import sys
from pathlib import Path
from datetime import date, timedelta

from config import WEB_HOST, WEB_PORT, LMS_TYPE, LMS_DOWNLOADS_DIR
from db.database import Database
from pipeline import StudyPipeline
from scheduler.cron_scheduler import StudyScheduler
from bot.telegram_bot import StudyTelegramBot
from exam.exam_engine import ExamEngine
import uvicorn

def seed_sample_data():
    """Seeds rich sample course slides, lectures, and exams for instant demonstration."""
    print("[Seed] Creating sample lecture decks and course hierarchy...")
    db = Database()
    exam_engine = ExamEngine(db=db)

    # 1. Create Sample CS301 (Operating Systems) lecture
    cs_dir = LMS_DOWNLOADS_DIR / "CS301_Operating_Systems" / "Week_01"
    cs_dir.mkdir(parents=True, exist_ok=True)
    cs_lecture_file = cs_dir / "Lec01_Virtual_Memory_and_Paging.txt"

    with open(cs_lecture_file, "w", encoding="utf-8") as f:
        f.write("""# Lecture 1: Virtual Memory, Paging, and Page Faults
## Virtual Memory Architecture
Virtual memory is a memory management technique that provides an idealized abstraction of the storage resources that are actually available on a given machine. It enables programs to run without requiring the entire address space to reside contiguously in physical RAM.

## The Memory Management Unit (MMU)
The Memory Management Unit (MMU) is a dedicated hardware component responsible for translating virtual addresses generated by the CPU into physical addresses in DRAM using Page Tables.

## Paging Mechanics and Page Size
Paging is a memory management scheme by which a computer stores and retrieves data from secondary storage for use in main memory in fixed-size blocks called pages. A typical standard page size in x86 architectures is 4096 bytes (4 KB).

## Translation Lookaside Buffer (TLB)
A Translation Lookaside Buffer (TLB) is a high-speed hardware associative cache that stores recent virtual-to-physical address mappings to avoid costly page table walks in main memory.

## Page Fault Exception Handling
A Page Fault is a hardware interrupt raised by the MMU when a program attempts to access a page that is mapped in the virtual address space but not currently loaded into physical memory. The operating system kernel traps the fault, brings the required page from disk (swap space) into an available RAM frame, updates the page table entry valid bit, and restarts the instruction.
""")

    # 2. Create Sample CS101 (Data Structures & Algorithms) lecture
    algo_dir = LMS_DOWNLOADS_DIR / "CS101_Algorithms" / "Week_01"
    algo_dir.mkdir(parents=True, exist_ok=True)
    algo_lecture_file = algo_dir / "Lec01_Asymptotic_Notation_and_Hash_Tables.txt"

    with open(algo_lecture_file, "w", encoding="utf-8") as f:
        f.write("""# Lecture 1: Asymptotic Complexity & Hash Collision Resolution
## Big-O Notation
Big-O Notation characterizes functions according to their growth rates: different functions with the same growth rate may be represented using the same O notation. It provides an asymptotic upper bound on the running time of an algorithm in the worst-case scenario.

## Hash Table Fundamentals
A Hash Table is an associative array data structure that maps keys to values using a mathematical hash function that computes an index into an array of buckets or slots.

## Collision Resolution: Separate Chaining vs Open Addressing
Separate Chaining handles collisions by maintaining a linked list or balanced tree at each bucket index to store colliding entries. In contrast, Open Addressing stores all elements directly in the hash table array and searches for alternative empty slots using probing sequences such as linear probing, quadratic probing, or double hashing.

## Amortized Time Complexity
Amortized Analysis analyzes an algorithm's complexity by considering the total cost of a sequence of operations averaged over the number of operations performed, guaranteeing worst-case performance per sequence even if an individual operation (like dynamic array resizing) is expensive.
""")

    # 3. Add upcoming exam dates
    today = date.today()
    exam_engine.add_exam(
        course_id="CS301_Operating_Systems",
        exam_title="Midterm Assessment: Memory & Processes",
        exam_date_str=(today + timedelta(days=6)).isoformat(),
        target_score=90,
        notes="High-yield focus on virtual memory, TLB hit rates, and page replacement policies."
    )
    exam_engine.add_exam(
        course_id="CS101_Algorithms",
        exam_title="Final Comprehensive Examination",
        exam_date_str=(today + timedelta(days=18)).isoformat(),
        target_score=85,
        notes="All data structures, trees, hashing, and dynamic programming."
    )

    # 4. Run pipeline on the seeded files
    print("[Seed] Ingesting seeded lectures through study pipeline...")
    pipeline = StudyPipeline(db=db)
    pipeline.run_sync("folder")
    processed = pipeline.process_pending_files()
    print(f"[Seed] Done! Successfully generated study packages for {len(processed)} lectures.")

def main():
    parser = argparse.ArgumentParser(description="SynapseLMS: Automated Study System")
    subparsers = parser.add_subparsers(dest="command", help="Command to run")

    # Command: run (start web dashboard)
    p_run = subparsers.add_parser("run", help="Start the Web Dashboard and API server")
    p_run.add_argument("--host", default=WEB_HOST, help="Web server host")
    p_run.add_argument("--port", type=int, default=WEB_PORT, help="Web server port")

    # Command: sync (sync files from LMS)
    p_sync = subparsers.add_parser("sync", help="Sync files from LMS (folder, moodle, or canvas)")
    p_sync.add_argument("--lms", default=LMS_TYPE, choices=["folder", "moodle", "canvas"], help="LMS source")

    # Command: generate (process pending lectures)
    subparsers.add_parser("generate", help="Process pending lectures and generate study materials")

    # Command: scheduler (run cron scheduler)
    subparsers.add_parser("scheduler", help="Run background daily 7 PM & weekend quiz scheduler")

    # Command: bot (start telegram bot)
    subparsers.add_parser("bot", help="Run interactive Telegram Bot")

    # Command: generate-mcqs (on-demand AI MCQ generation)
    p_mcq = subparsers.add_parser("generate-mcqs", help="Generate AI MCQs on demand from course lecture slides")
    p_mcq.add_argument("--course", default="all", help="Course ID or 'all'")
    p_mcq.add_argument("--count", type=int, default=10, help="Number of MCQs to generate (default: 10)")

    # Command: seed (seed sample courses for testing)
    subparsers.add_parser("seed", help="Seed sample course slides and exams for testing")

    # Command: nust-login (authenticate with NUST LMS and sync)
    p_nust = subparsers.add_parser("nust-login", help="Log in to NUST LMS (lms.nust.edu.pk) and sync all courses")
    p_nust.add_argument("--username", required=True, help="NUST Qalam / LMS Username")
    p_nust.add_argument("--password", required=True, help="NUST Qalam / LMS Password")

    args = parser.parse_args()

    if args.command == "run" or args.command is None:
        host = getattr(args, "host", WEB_HOST)
        port = getattr(args, "port", WEB_PORT)
        print(f"\n==================================================================")
        print(f">> SynapseLMS Automated Study System running at:")
        print(f"   http://{host}:{port}")
        print(f"==================================================================\n")
        uvicorn.run("web.server:app", host=host, port=port, reload=False)

    elif args.command == "generate-mcqs":
        pipeline = StudyPipeline()
        print(f"[Generate] Generating {args.count} AI MCQs for course '{args.course}'...")
        mcqs = pipeline.generate_mcqs_for_course(course_id=args.course, count=args.count)
        print(f"[Generate] Done! Generated and stored {len(mcqs)} new AI MCQs in the question bank.")
        for idx, q in enumerate(mcqs, 1):
            print(f"\n  Q{idx}: {q.get('q')}")
            for o_idx, opt in enumerate(q.get('options', [])):
                mark = "*" if o_idx == q.get('answer') else " "
                print(f"    [{mark}] {chr(65+o_idx)}. {opt}")
            print(f"    Source: {q.get('source')}")

    elif args.command == "nust-login":
        pipeline = StudyPipeline()
        print(f"[NUST LMS] Authenticating user '{args.username}' at https://lms.nust.edu.pk...")
        res = pipeline.moodle.login_with_credentials(args.username, args.password)
        if res.get("success"):
            print(f"[NUST LMS] Successfully authenticated! Token acquired.")
            print(f"[NUST LMS] Discovering enrolled courses...")
            courses = pipeline.moodle.get_enrolled_courses()
            print(f"[NUST LMS] Enrolled in {len(courses)} courses:")
            for c in courses:
                print(f"  - {c.get('fullname')} ({c.get('shortname')})")
            print(f"[NUST LMS] Syncing slide decks and course contents...")
            pipeline.run_sync("moodle")
            processed = pipeline.process_pending_files()
            print(f"[NUST LMS] Completed! {len(processed)} lecture decks ingested.")
        else:
            print(f"[NUST LMS] Login failed: {res.get('error')}")

    elif args.command == "sync":
        pipeline = StudyPipeline()
        pipeline.run_sync(args.lms)

    elif args.command == "generate":
        pipeline = StudyPipeline()
        pipeline.process_pending_files()

    elif args.command == "scheduler":
        sched = StudyScheduler()
        sched.start_scheduler()

    elif args.command == "bot":
        bot = StudyTelegramBot()
        bot.run()

    elif args.command == "seed":
        seed_sample_data()

if __name__ == "__main__":
    main()
